# Foundry Configuration File for IthacaAccountV2
# Extends configuration from account module

[profile.default]
evm_version = "prague"
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
gas_limit = 100_000_000
solc_version = "0.8.28"
libs = ["lib"]
src = "src"
test = "test"
script = "script"

# Remappings for zkEmail and other dependencies
remappings = [
  "solady/=lib/solady/src/",
  "forge-std/=lib/forge-std/src/",
  "@account/=../account/src/"
]

# Allow access to parent directories
fs_permissions = [{ access = "read", path = "../" }, { access = "read", path = "../../lib" }]
allow_paths = ["../../lib", "../account"]

[fmt]
line_length = 100

[profile.default.fuzz]
runs = 256

[invariant]
depth = 15
runs = 10