packages:
  - "apps/*"
  - "docker/*"
  - "examples/*"
  - "src"
  - "test/e2e"

catalog:
  "@ariakit/react": "^0.4.17"
  "@ariakit/tailwind": "^0.1.7"
  "@iconify/json": "^2.2.354"
  "@sentry/react": "^9"
  "@sentry/vite-plugin": "^3"
  "@svgr/core": "^8.1.0"
  "@svgr/plugin-jsx": "^8.1.0"
  "@tanstack/query-sync-storage-persister": "^5.74.3"
  "@tanstack/react-query": "^5.74.3"
  "@tanstack/react-query-persist-client": "^5.74.3"
  "@tanstack/react-router": "^1.114.25"
  "@tanstack/router-plugin": "^1.114.17"
  "@tanstack/react-query-devtools": "^5.81.5"
  "@tanstack/react-router-devtools": "^1.114.25"
  "@types/node": "^22.15.32"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "@wagmi/core": "^2.17.2"
  cva: "npm:class-variance-authority@^0.7.1"
  globals: "^16.2.0"
  ox: "^0.8.4"
  prool: "^0.0.23"
  react: "^19"
  react-dom: "^19"
  sonner: "^2.0.5"
  tailwindcss: "^4.1.11"
  "@tailwindcss/vite": "^4.1.11"
  tw-animate-css: "^1.3.4"
  typescript: "^5.8.3"
  unplugin-icons: "^22.1.0"
  viem: "^2.30.6"
  vite: "^6.0.7"
  vitest: "^3.1.1"
  vite-plugin-mkcert: "^1.17.8"
  wagmi: "^2.15.4"
  zustand: "^5.0.3"
  "@vitejs/plugin-react": "^4.6.0"
