name: Deploy Workers

on:
  push:
    branches: [main]
    paths:
      - 'apps/service/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: 'Deploy'
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    strategy:
      matrix:
        worker:
          - service
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: 🔸 Cloudflare Workers - Deploy ${{ matrix.worker }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: pnpm --filter ${{ matrix.worker }} run deploy
