name: Verify
on:
  workflow_call:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Check code
        run: pnpm check

      - name: Check types
        run: pnpm check:types

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build
        run: pnpm build

      - name: Check build
        run: pnpm check:build

      - name: Check for unused files, dependencies, and exports
        run: pnpm check:knip

      - name: Check size
        run: pnpm check:size

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit