/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bdef260aab7a6c376a822abd88b3d29c)
declare namespace Cloudflare {
  interface Env {
    NONCE_STORE: KVNamespace
    BETTER_AUTH_SIWE_DOMAIN: string
    BETTER_AUTH_SECRET: string
    BETTER_AUTH_URL: string
    DB: D1Database
  }
}
interface Env extends Cloudflare.Env {}
